### ISSUE TITLE
Separate Font options for WR time and have it actually work

### ISSUE THREAD

**Issue by xwmtp** [xTVaser/src-twitch-ext#48]
**This is a...**  

- [ ] Bug Report  
- [X] Feature Request

## Brief Description

I would like the option to change the color of the wr times (yellow by default).

## (If Feature Request) Describe it. 

I love how customizable the panel is in general. The only color that cannot be changed seems to be that of the wr times (except for the rainbow cycling option). Please tell me if I have overlooked it. Personally I like to customize the panel to a certain minimalistic style, and yellow does not seem to fit.

**Comment by xTVaser** [comment]
Hey!

I'm pretty sure that this option is supposed to change both the WR and PB time's color/font, but atm it seems to only effect the PBs. 
![image](https://user-images.githubusercontent.com/13153231/34448489-d1f474b0-ecbb-11e7-9ef4-860a1cf12a33.png)

Seems like I broke it because changing the font affects both, but the color only changes the PB time.  They should be separated anyway in my opinion.

This brings up a bigger issue in my mind and that is that the configuration page is imo very unnecessarily cluttered and I have a few ideas for how I can make it a lot better so I'll do both at the same time.  I mostly was focused on getting the actual panel on the profile working and being fully-featured as it is obviously more important, now that that is mostly done I can work on the configuration side of things again.

Thanks for bringing this to my attention, if you have any other suggestions, feel free to let me know.

**Comment by xTVaser** [comment]
Separate options added, shifting to parent issue #57 to make sure all configuration settings work (these included)
