### ISSUE TITLE
Scoreboard position

### ISSUE THREAD

**Issue by Khrinx** [xTVaser/src-twitch-ext#65]
**This is a...**  

- [ ] Bug Report  
- [X] Feature Request

## Brief Description

Possibility to add what position you're in. 1st, 2nd, 3rd, etc.

![image](https://user-images.githubusercontent.com/10628975/37454619-560d249e-283b-11e8-9eb0-56ca0bb0298d.png)

**Comment by HexTree** [comment]
Having this would definitely encourage me to switch to this extension instead of writing out my PBs in manual text. Leaderboard rank is the canonical measure of relative performance, since most viewers don't have any sense of whether a time is good or not unless they know the game and its speedruns well.

**Comment by xTVaser** [comment]
This feature was added to the new v2 version (currently being reviewed by Twitch).  It's off by default just because horizontal space is precious, but you can enable it by making a custom theme. 
![image](https://github.com/xTVaser/src-twitch-ext/assets/13153231/77f5565c-78b1-491b-bd24-06ac541ae68c)
