### ISSUE TITLE
It would be nice if I could replace the green/blue title background

### ISSUE THREAD

**Issue by 1stKingSolomon** [xTVaser/src-twitch-ext#66]
**This is a...**  

- [] Bug Report  
- [X] Feature Request

## Brief Description

It would be nice if there was the possibility to change the background of the cover picture.

## (If Feature Request) Describe it. 

As I've already seen, there are currently 2 backgrounds, one bright and one dark. I think it would be cool if it were possible to upload images up to a certain size or just use the same size of the current image and then use it.

**Comment by xTVaser** [comment]
Hmm, are you referring to the background of the panel title?  You can use the default picture, or a solid color, or a horizontal / vertical gradient.  

![image](https://user-images.githubusercontent.com/13153231/43040147-3d4c3dda-8d0a-11e8-9b83-a74907962aba.png)

Theres also an option to change the background color of the content section of the extension

I don't think I am able to let anyone use any image they want, as it would only take 1 person to use some sort of offensive image and then I will run into issues with Twitch.  This is why I've limited it to colors and gradients.

I am open to including more default included pictures though in the future, but they would have to added by me, rather than an option in the extension unfortunately.

**Comment by xTVaser** [comment]
separate title has been removed in v2
