### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by Zedb0T** [xTVaser/src-twitch-ext#83]
Panel no longer functions after SRC update.
![image](https://github.com/xTVaser/src-twitch-ext/assets/89345505/20539430-73fe-47a4-92cc-c33055dbde95)

**Comment by binaryribbit** [comment]
I am having the same problem

**Comment by xTVaser** [comment]
Should be fixed now.

The problem was I revoked the server's twitch credential while working on https://github.com/xTVaser/src-twitch-ext/pull/84 

But these kind of problems completely go away with v2 (currently being reviewed by twitch), as I no longer will store/manage the configuration on my own server.
